### ISSUE TITLE
Inconsistent with the original dataset

### ISSUE THREAD

**Issue by lyancynthia** [LibCity/Bigscity-LibCity-Datasets#47]
Hi,

May I know how did you calculate the statistics for user numbers? They are different from the original paper which published the dataset you used.

<img width="875" alt="image" src="https://github.com/LibCity/Bigscity-LibCity-Datasets/assets/64658248/3d8a7d25-b7c0-4b28-8bc7-566b08443436">

<img width="890" alt="image" src="https://github.com/LibCity/Bigscity-LibCity-Datasets/assets/64658248/958b0713-b5a3-4aff-be01-6bcb7a745e99">

**Comment by aptx1231** [comment]
@WenMellors

**Comment by WenMellors** [comment]
Actually, I don't know anything about this. I downloaded this data from [Dingqi Yang's homepage](https://sites.google.com/site/yangdingqi/home/foursquare-dataset#h.p_ID_46). During processing, I did not delete the data. Only one mistake is that Geo's stats are undercounted by one, because I overlooked that we start numbering from 0. In the paper, the author eliminated inactive users, which may be a reson caused by this operation.
